---
- name: "Adding SSH UMCCR team public keys to the instance"
  become: false
  shell: |
      org_ssh_keys=$(curl -s https://api.github.com/orgs/umccr/members | jq -r .[].html_url | sed 's/$/.keys/')
      echo $org_ssh_keys
      for ssh_key in $org_ssh_keys
      do
              wget $ssh_key -O - >> ~/.ssh/authorized_keys
      done